# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/matt/Downloads/cmake-3.13.3/bin/cmake

# The command to remove a file.
RM = /home/matt/Downloads/cmake-3.13.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matt/Documents/CudaRT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matt/Documents/CudaRT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/matt/Downloads/cmake-3.13.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/matt/Downloads/cmake-3.13.3/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matt/Documents/CudaRT/CMakeFiles /home/matt/Documents/CudaRT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matt/Documents/CudaRT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named geometrylib

# Build rule for target.
geometrylib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 geometrylib
.PHONY : geometrylib

# fast build rule for target.
geometrylib/fast:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/build
.PHONY : geometrylib/fast

#=============================================================================
# Target rules for targets named contextlib

# Build rule for target.
contextlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 contextlib
.PHONY : contextlib

# fast build rule for target.
contextlib/fast:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/build
.PHONY : contextlib/fast

#=============================================================================
# Target rules for targets named CudaRT

# Build rule for target.
CudaRT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CudaRT
.PHONY : CudaRT

# fast build rule for target.
CudaRT/fast:
	$(MAKE) -f CMakeFiles/CudaRT.dir/build.make CMakeFiles/CudaRT.dir/build
.PHONY : CudaRT/fast

#=============================================================================
# Target rules for targets named rendererlib

# Build rule for target.
rendererlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rendererlib
.PHONY : rendererlib

# fast build rule for target.
rendererlib/fast:
	$(MAKE) -f CMakeFiles/rendererlib.dir/build.make CMakeFiles/rendererlib.dir/build
.PHONY : rendererlib/fast

src/context/launcher.o: src/context/launcher.cpp.o

.PHONY : src/context/launcher.o

# target to build an object file
src/context/launcher.cpp.o:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/launcher.cpp.o
.PHONY : src/context/launcher.cpp.o

src/context/launcher.i: src/context/launcher.cpp.i

.PHONY : src/context/launcher.i

# target to preprocess a source file
src/context/launcher.cpp.i:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/launcher.cpp.i
.PHONY : src/context/launcher.cpp.i

src/context/launcher.s: src/context/launcher.cpp.s

.PHONY : src/context/launcher.s

# target to generate assembly for a file
src/context/launcher.cpp.s:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/launcher.cpp.s
.PHONY : src/context/launcher.cpp.s

src/context/terminal_launcher.o: src/context/terminal_launcher.cpp.o

.PHONY : src/context/terminal_launcher.o

# target to build an object file
src/context/terminal_launcher.cpp.o:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/terminal_launcher.cpp.o
.PHONY : src/context/terminal_launcher.cpp.o

src/context/terminal_launcher.i: src/context/terminal_launcher.cpp.i

.PHONY : src/context/terminal_launcher.i

# target to preprocess a source file
src/context/terminal_launcher.cpp.i:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/terminal_launcher.cpp.i
.PHONY : src/context/terminal_launcher.cpp.i

src/context/terminal_launcher.s: src/context/terminal_launcher.cpp.s

.PHONY : src/context/terminal_launcher.s

# target to generate assembly for a file
src/context/terminal_launcher.cpp.s:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/terminal_launcher.cpp.s
.PHONY : src/context/terminal_launcher.cpp.s

src/context/window.o: src/context/window.cpp.o

.PHONY : src/context/window.o

# target to build an object file
src/context/window.cpp.o:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/window.cpp.o
.PHONY : src/context/window.cpp.o

src/context/window.i: src/context/window.cpp.i

.PHONY : src/context/window.i

# target to preprocess a source file
src/context/window.cpp.i:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/window.cpp.i
.PHONY : src/context/window.cpp.i

src/context/window.s: src/context/window.cpp.s

.PHONY : src/context/window.s

# target to generate assembly for a file
src/context/window.cpp.s:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/window.cpp.s
.PHONY : src/context/window.cpp.s

src/context/windowed_launcher.o: src/context/windowed_launcher.cpp.o

.PHONY : src/context/windowed_launcher.o

# target to build an object file
src/context/windowed_launcher.cpp.o:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/windowed_launcher.cpp.o
.PHONY : src/context/windowed_launcher.cpp.o

src/context/windowed_launcher.i: src/context/windowed_launcher.cpp.i

.PHONY : src/context/windowed_launcher.i

# target to preprocess a source file
src/context/windowed_launcher.cpp.i:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/windowed_launcher.cpp.i
.PHONY : src/context/windowed_launcher.cpp.i

src/context/windowed_launcher.s: src/context/windowed_launcher.cpp.s

.PHONY : src/context/windowed_launcher.s

# target to generate assembly for a file
src/context/windowed_launcher.cpp.s:
	$(MAKE) -f CMakeFiles/contextlib.dir/build.make CMakeFiles/contextlib.dir/src/context/windowed_launcher.cpp.s
.PHONY : src/context/windowed_launcher.cpp.s

src/geometry/bvh.o: src/geometry/bvh.cpp.o

.PHONY : src/geometry/bvh.o

# target to build an object file
src/geometry/bvh.cpp.o:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/bvh.cpp.o
.PHONY : src/geometry/bvh.cpp.o

src/geometry/bvh.i: src/geometry/bvh.cpp.i

.PHONY : src/geometry/bvh.i

# target to preprocess a source file
src/geometry/bvh.cpp.i:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/bvh.cpp.i
.PHONY : src/geometry/bvh.cpp.i

src/geometry/bvh.s: src/geometry/bvh.cpp.s

.PHONY : src/geometry/bvh.s

# target to generate assembly for a file
src/geometry/bvh.cpp.s:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/bvh.cpp.s
.PHONY : src/geometry/bvh.cpp.s

src/geometry/camera.o: src/geometry/camera.cu.o

.PHONY : src/geometry/camera.o

# target to build an object file
src/geometry/camera.cu.o:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/camera.cu.o
.PHONY : src/geometry/camera.cu.o

src/geometry/camera.i: src/geometry/camera.cu.i

.PHONY : src/geometry/camera.i

# target to preprocess a source file
src/geometry/camera.cu.i:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/camera.cu.i
.PHONY : src/geometry/camera.cu.i

src/geometry/camera.s: src/geometry/camera.cu.s

.PHONY : src/geometry/camera.s

# target to generate assembly for a file
src/geometry/camera.cu.s:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/camera.cu.s
.PHONY : src/geometry/camera.cu.s

src/geometry/geometry.o: src/geometry/geometry.cu.o

.PHONY : src/geometry/geometry.o

# target to build an object file
src/geometry/geometry.cu.o:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/geometry.cu.o
.PHONY : src/geometry/geometry.cu.o

src/geometry/geometry.i: src/geometry/geometry.cu.i

.PHONY : src/geometry/geometry.i

# target to preprocess a source file
src/geometry/geometry.cu.i:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/geometry.cu.i
.PHONY : src/geometry/geometry.cu.i

src/geometry/geometry.s: src/geometry/geometry.cu.s

.PHONY : src/geometry/geometry.s

# target to generate assembly for a file
src/geometry/geometry.cu.s:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/geometry.cu.s
.PHONY : src/geometry/geometry.cu.s

src/geometry/scene.o: src/geometry/scene.cpp.o

.PHONY : src/geometry/scene.o

# target to build an object file
src/geometry/scene.cpp.o:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/scene.cpp.o
.PHONY : src/geometry/scene.cpp.o

src/geometry/scene.i: src/geometry/scene.cpp.i

.PHONY : src/geometry/scene.i

# target to preprocess a source file
src/geometry/scene.cpp.i:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/scene.cpp.i
.PHONY : src/geometry/scene.cpp.i

src/geometry/scene.s: src/geometry/scene.cpp.s

.PHONY : src/geometry/scene.s

# target to generate assembly for a file
src/geometry/scene.cpp.s:
	$(MAKE) -f CMakeFiles/geometrylib.dir/build.make CMakeFiles/geometrylib.dir/src/geometry/scene.cpp.s
.PHONY : src/geometry/scene.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/CudaRT.dir/build.make CMakeFiles/CudaRT.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/CudaRT.dir/build.make CMakeFiles/CudaRT.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/CudaRT.dir/build.make CMakeFiles/CudaRT.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/renderer/parallel_renderer.o: src/renderer/parallel_renderer.cu.o

.PHONY : src/renderer/parallel_renderer.o

# target to build an object file
src/renderer/parallel_renderer.cu.o:
	$(MAKE) -f CMakeFiles/rendererlib.dir/build.make CMakeFiles/rendererlib.dir/src/renderer/parallel_renderer.cu.o
.PHONY : src/renderer/parallel_renderer.cu.o

src/renderer/parallel_renderer.i: src/renderer/parallel_renderer.cu.i

.PHONY : src/renderer/parallel_renderer.i

# target to preprocess a source file
src/renderer/parallel_renderer.cu.i:
	$(MAKE) -f CMakeFiles/rendererlib.dir/build.make CMakeFiles/rendererlib.dir/src/renderer/parallel_renderer.cu.i
.PHONY : src/renderer/parallel_renderer.cu.i

src/renderer/parallel_renderer.s: src/renderer/parallel_renderer.cu.s

.PHONY : src/renderer/parallel_renderer.s

# target to generate assembly for a file
src/renderer/parallel_renderer.cu.s:
	$(MAKE) -f CMakeFiles/rendererlib.dir/build.make CMakeFiles/rendererlib.dir/src/renderer/parallel_renderer.cu.s
.PHONY : src/renderer/parallel_renderer.cu.s

src/renderer/renderer.o: src/renderer/renderer.cu.o

.PHONY : src/renderer/renderer.o

# target to build an object file
src/renderer/renderer.cu.o:
	$(MAKE) -f CMakeFiles/rendererlib.dir/build.make CMakeFiles/rendererlib.dir/src/renderer/renderer.cu.o
.PHONY : src/renderer/renderer.cu.o

src/renderer/renderer.i: src/renderer/renderer.cu.i

.PHONY : src/renderer/renderer.i

# target to preprocess a source file
src/renderer/renderer.cu.i:
	$(MAKE) -f CMakeFiles/rendererlib.dir/build.make CMakeFiles/rendererlib.dir/src/renderer/renderer.cu.i
.PHONY : src/renderer/renderer.cu.i

src/renderer/renderer.s: src/renderer/renderer.cu.s

.PHONY : src/renderer/renderer.s

# target to generate assembly for a file
src/renderer/renderer.cu.s:
	$(MAKE) -f CMakeFiles/rendererlib.dir/build.make CMakeFiles/rendererlib.dir/src/renderer/renderer.cu.s
.PHONY : src/renderer/renderer.cu.s

src/renderer/sequential_renderer.o: src/renderer/sequential_renderer.cu.o

.PHONY : src/renderer/sequential_renderer.o

# target to build an object file
src/renderer/sequential_renderer.cu.o:
	$(MAKE) -f CMakeFiles/rendererlib.dir/build.make CMakeFiles/rendererlib.dir/src/renderer/sequential_renderer.cu.o
.PHONY : src/renderer/sequential_renderer.cu.o

src/renderer/sequential_renderer.i: src/renderer/sequential_renderer.cu.i

.PHONY : src/renderer/sequential_renderer.i

# target to preprocess a source file
src/renderer/sequential_renderer.cu.i:
	$(MAKE) -f CMakeFiles/rendererlib.dir/build.make CMakeFiles/rendererlib.dir/src/renderer/sequential_renderer.cu.i
.PHONY : src/renderer/sequential_renderer.cu.i

src/renderer/sequential_renderer.s: src/renderer/sequential_renderer.cu.s

.PHONY : src/renderer/sequential_renderer.s

# target to generate assembly for a file
src/renderer/sequential_renderer.cu.s:
	$(MAKE) -f CMakeFiles/rendererlib.dir/build.make CMakeFiles/rendererlib.dir/src/renderer/sequential_renderer.cu.s
.PHONY : src/renderer/sequential_renderer.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... geometrylib"
	@echo "... contextlib"
	@echo "... CudaRT"
	@echo "... rendererlib"
	@echo "... src/context/launcher.o"
	@echo "... src/context/launcher.i"
	@echo "... src/context/launcher.s"
	@echo "... src/context/terminal_launcher.o"
	@echo "... src/context/terminal_launcher.i"
	@echo "... src/context/terminal_launcher.s"
	@echo "... src/context/window.o"
	@echo "... src/context/window.i"
	@echo "... src/context/window.s"
	@echo "... src/context/windowed_launcher.o"
	@echo "... src/context/windowed_launcher.i"
	@echo "... src/context/windowed_launcher.s"
	@echo "... src/geometry/bvh.o"
	@echo "... src/geometry/bvh.i"
	@echo "... src/geometry/bvh.s"
	@echo "... src/geometry/camera.o"
	@echo "... src/geometry/camera.i"
	@echo "... src/geometry/camera.s"
	@echo "... src/geometry/geometry.o"
	@echo "... src/geometry/geometry.i"
	@echo "... src/geometry/geometry.s"
	@echo "... src/geometry/scene.o"
	@echo "... src/geometry/scene.i"
	@echo "... src/geometry/scene.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/renderer/parallel_renderer.o"
	@echo "... src/renderer/parallel_renderer.i"
	@echo "... src/renderer/parallel_renderer.s"
	@echo "... src/renderer/renderer.o"
	@echo "... src/renderer/renderer.i"
	@echo "... src/renderer/renderer.s"
	@echo "... src/renderer/sequential_renderer.o"
	@echo "... src/renderer/sequential_renderer.i"
	@echo "... src/renderer/sequential_renderer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

